//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Content type.
	/// </summary>
	public enum ContentType
	{
		Text = 0, 				//Text
		Image = 1,				//Image 
		News = 2,				//News 
		Music = 3,				//Music 
		Video = 4,				//Video 
		App = 5, 				//App
		NonGif = 6,				//Non Gif Image 
		Gif = 7,				//Gif Image 
		File = 8				//File
	};

}

