//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Content type.
	/// </summary>
	public class ContentType
	{	      		
		public const String Auto = "0";					//Auto			自动
		public const String Text = "1"; 				//文字分享
		public const String Image = "2";				//图文分享
		public const String Webpage = "4";				//链接分享
		public const String Music = "5";				//音乐分享 
		public const String Video = "6";				//视频分享 
		public const String App = "7"; 					//应用分享
		public const String File = "8";					//附件分享
		public const String Emoji = "9";				//表情分享
	}

}

