//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;

namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Event result listener.
	/// </summary>
	public delegate void EventResultListener (ResponseState state, PlatformType type, Hashtable error);

}

