//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Platform type.
	/// </summary>
	public enum PlatformType
	{
		Unknown = 0,
		SinaWeibo = 1,			//Sina Weibo         
		TencentWeibo = 2,		//Tencent Weibo          
		DouBan = 5,				//Dou Ban           
		QZone = 6, 				//QZone           
		Renren = 7,				//Ren Ren           
		Kaixin = 8,				//Kai Xin          
		Pengyou = 9,			//Friends          
		Facebook = 10,			//Facebook         
		Twitter = 11,			//Twitter         
		Evernote = 12,			//Evernote        
		Foursquare = 13,		//Foursquare      
		GooglePlus = 14,		//Google+       
		Instagram = 15,			//Instagram      
		LinkedIn = 16,			//LinkedIn       
		Tumblr = 17,			//Tumblr         
		Mail = 18, 				//Mail          
		SMS = 19,				//SMS           
		Print = 20, 			//Print       
		Copy = 21,				//Copy             
		WeChatSession = 22,		//WeChat Session    
		WeChatTimeline = 23,	//WeChat Timeline   
		QQ = 24,				//QQ              
		Instapaper = 25,		//Instapaper       
		Pocket = 26,			//Pocket           
		YouDaoNote = 27, 		//You Dao Note     
		SohuKan = 28, 			//Sohu Sui Shen Kan         
		Pinterest = 30, 		//Pinterest    
		Flickr = 34,			//Flickr          
		Dropbox = 35,			//Dropbox          
		VKontakte = 36,			//VKontakte       
		WeChatFav = 37,			//WeChat Favorited        
		YiXinSession = 38, 		//YiXin Session   
		YiXinTimeline = 39,		//YiXin Timeline   
		YiXinFav = 40,			//YiXin Favorited  
		MingDao = 41,          	//明道
		Line = 42,             	//Line
		WhatsApp = 43,         	//Whats App
		KakaoTalk = 44,         //KakaoTalk
		KakaoStory = 45,        //KakaoStory 
		FacebookMessenger = 46, //FacebookMessenger
		Bluetooth = 48,         //Bluetooth
		Alipay = 50,
		EvernoteInternational = 996,//Evernote InternationaL Edition
		WechatPlatform = 997,   //Wechat Series
		QQPlatform = 998,		//QQ Series
		Any = 999 				//Any Platform  
	}

}

