//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
namespace cn.sharesdk.unity3d{
	public abstract class ShareSDKUtilsInterface{

		/// <summary>
		/// Sets the platform config.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="configs">Configs.</param>
		public abstract void RigisterAppAndSetPlatformConfig (String appKey, Hashtable configs);
		
		/// <summary>
		/// Authorize the specified platform.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void Authorize (PlatformType platform);
		
		/// <summary>
		/// Removes the account of the specified platform.
		/// </summary>
		/// <param name="platform">Platform.</param>
		public abstract void CancelAuthorize (PlatformType platform);
		
		/// <summary>
		/// Determine weather the account of the specified platform is valid.
		/// </summary>
		/// <returns><c>true</c>, if valid was ised, <c>false</c> otherwise.</returns>
		/// <param name="platform">Platform.</param>
		public abstract bool IsAuthorizedValid (PlatformType platform);

		/// <summary>
		/// Determine weather the APP-Client of platform is valid.
		/// </summary>
		/// <returns><c>true</c>, if valid was install, <c>false</c> otherwise.</returns>
		/// <param name="platform">Platform.</param>
		public abstract bool IsClientValid (PlatformType platform);

		/// <summary>
		/// Request the user info of the specified platform.
		/// </summary>
		/// <param name="platform">Platform.</param>
		public abstract void GetUserInfo (PlatformType platform);

		/// <summary>
		/// Share the content to the specified platform with api.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="content">Content.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void ShareContent (PlatformType platform, Hashtable content);

		/// <summary>
		/// Share the content to the specified platform with api.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="content">Content.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void ShareContent (PlatformType[] platforms, Hashtable content);
		
		/// <summary>
		/// GUI share.
		/// </summary>
		/// <param name="content">Content.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void ShowShareMenu (PlatformType[] platforms, Hashtable content, int x, int y);
		
		/// <summary>
		/// OGUI share to the specified platform. 
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="content">Content.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void ShowShareView (PlatformType platform, Hashtable content);

		/// <summary>
		/// Gets the friend list.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="count">Count.</param>
		/// <param name="page">Page.</param>
		/// <param name="resultHandler">Result handler.</param>
		public abstract void GetFriendList (PlatformType platform, int count, int page);
		
		
		/// <summary>
		/// Follows the friend.
		/// </summary>
		/// <param name="platform">Platform.</param>
		/// <param name="account">Account.</param>
		public abstract void AddFriend (PlatformType platform, String account);

		/// <summary>
		/// Gets the auth info.
		/// </summary>
		/// <param name="platform">Platform.</param>
		public abstract Hashtable GetAuthInfo (PlatformType platform);

		/// <summary>
		/// the setting of SSO
		/// </summary>
		/// <param name="disable">If set to <c>true</c> disable.</param>
		public abstract void CloseSSOWhenAuthorize (Boolean open);

	}
}

