//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine; 
using System;
using System.Collections;
using System.Collections.Generic;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Content type.
	/// </summary>
	public class ShareContent
	{	      		
		Hashtable shareParams = new Hashtable();

		public void SetTitle(String title) {
			shareParams["title"] = title;
		}

		public void SetText(String text) {
			shareParams["text"] = text;
		}

		public void SetUrl(String url) {
			shareParams["url"] = url;
		}

		public void SetTitleUrl(String titleUrl) {
			shareParams["titleUrl"] = titleUrl;
		}

		public void SetImagePath(String imagePath) {
			shareParams["imagePath"] = imagePath;
		}

		public void SetImageUrl(String imageUrl) {
			shareParams["imageUrl"] = imageUrl;
		}

		public void SetFilePath(String filePath) {
			shareParams["filePath"] = filePath;
		}

		public void SetComment(String comment) {
			#if UNITY_ANDROID
			shareParams["comment"] = comment;
			#elif UNITY_IPHONE
			shareParams["description"] = comment;
			#endif
		}

		public void SetSite(String site) {
			shareParams["site"] = site;
		}

		public void SetSiteUrl(String siteUrl) {
			shareParams["siteUrl"] = siteUrl;
		}

		public void SetMusicUrl(String musicUrl) {
			shareParams["musicUrl"] = musicUrl;
		}

		public void SetShareType(int shareType) {
			if (shareType == 0) {
				shareType = 1;
			}
			shareParams["shareType"] = shareType;
		}

		public void SetAddress(String address) {
			shareParams["address"] = address;
		}
		
		public void SetLatitude(String latitude) {
			shareParams["latitude"] = latitude;
		}
			
		public void SetLongitude(String longitude) {
			shareParams["longitude"] = longitude;
		}

		public String GetShareParamsStr() {
			String jsonStr = MiniJSON.jsonEncode (shareParams);
			Debug.Log("ParseShareParams  ===>>> " + jsonStr );
			return jsonStr;
		}

		public Hashtable GetShareParams() {
			String jsonStr = MiniJSON.jsonEncode (shareParams);
			Debug.Log("ParseShareParams  ===>>> " + jsonStr );
			return shareParams;
		}
	}

}

