//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine; 
using System;
using System.Collections;
using System.Collections.Generic;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Content type.
	/// </summary>
	public class ShareContent
	{	      		
		Hashtable shareParams = new Hashtable();
		Hashtable customizeShareParams = new Hashtable();


		/*以下方法为定制基本分享内容字段的方法*/
		public void SetTitle(String title) {
			shareParams["title"] = title;
		}

		public void SetText(String text) {
			shareParams["text"] = text;
		}

		public void SetUrl(String url) {
			shareParams["url"] = url;
		}

		public void SetImageUrl(String imageUrl) {
			shareParams["imageUrl"] = imageUrl;
		}

		public void SetShareType(int shareType) {
			if (shareType == 0) {
				shareType = 1;
			}
			shareParams["shareType"] = shareType;
		}

		/*---------------------------------------*/
		/*以下方法为定制指定平台分享内容的时候可能用到的方法*/

		public void SetTitleUrl(String titleUrl) {
			shareParams["titleUrl"] = titleUrl;
		}

		public void SetFilePath(String filePath) {
			shareParams["filePath"] = filePath;
		}

		public void SetComment(String comment) {
			shareParams["comment"] = comment;
		}

		public void SetSite(String site) {
			shareParams["site"] = site;
		}

		public void SetSiteUrl(String siteUrl) {
			shareParams["siteUrl"] = siteUrl;
		}

		public void SetMusicUrl(String musicUrl) {
			shareParams["musicUrl"] = musicUrl;
		}

		public void SetAddress(String address) {
			shareParams["address"] = address;
		}
		
		public void SetLatitude(String latitude) {
			shareParams["latitude"] = latitude;
		}
			
		public void SetLongitude(String longitude) {
			shareParams["longitude"] = longitude;
		}

		public void SetObjectID(String objectId) {
			shareParams["objectID"] = objectId;
		}

		public void SetAlbumID(String albumId) {
			shareParams["AlbumID"] = albumId;
		}

		public void SetEmotionPath(String emotionPath){
			shareParams["emotionPath"] = emotionPath;
		}

		public void SetExtInfoPath(String extInfoPath){
			shareParams["extInfoPath"] = extInfoPath;
		}

		public void SetThumbImageUrl(String thumbImageUrl){
			shareParams["thumbImageUrl"] = thumbImageUrl;
		}


		//不同平台分享不同内容
		public void SetShareContentCustomize(PlatformType platform, ShareContent content) {
			customizeShareParams [(int)platform] = content.GetShareParamsStr();
		}

		public String GetShareParamsStr() {
			if (customizeShareParams.Count > 0) {
				shareParams["customizeShareParams"] = customizeShareParams;
			}
			String jsonStr = MiniJSON.jsonEncode (shareParams);
			Debug.Log("ParseShareParams  ===>>> " + jsonStr );
			return jsonStr;
		}

		public Hashtable GetShareParams() {
			if (customizeShareParams.Count > 0) {
				shareParams["customizeShareParams"] = customizeShareParams;
			}
			String jsonStr = MiniJSON.jsonEncode (shareParams);
			Debug.Log("ParseShareParams  ===>>> " + jsonStr );
			return shareParams;
		}
	}

}

